apiVersion: v1
kind: Secret
metadata:
  name: jfrog-cred
  namespace: taxi
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0cmlhbDIyYmpxcS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiYzJGcGNtRnRPa3BtY205blFERXlNelE9IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
